project_id = "uxjvtpmnnvxlvanedzxk"

[functions.ocr-image]
verify_jwt = false

[functions.validate-role-password]
verify_jwt = false

[functions.ocr-bill]
verify_jwt = false

[functions.ocr-storage]
verify_jwt = false

[functions.developer-company-admin]
verify_jwt = false
